[package]
name = "Spartacus"
description = "A tool for creating and verifying ring signatures."
version = "0.1.0"
edition = "2021"

[lib]
name = "spartacus"
path = "src/lib.rs"

[[bin]]
name = "Spartacus"
path = "src/main.rs"

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
secmem-proc = "0.3"

spartacus_storage = { path = "../spartacus_storage" }

[package.metadata.bundle]
identifier = "me.w-r.Spartacus"
icon = ["spartacus_head.png"]
